backend:
  name: test-repo
  repo: blueunars-space/docu_test
  branch: main

media_folder: "uploads"
public_folder: "/uploads"

collections:
  - name: "docs"
    label: "Docs"
    folder: "docs"
    create: true
    nested:
      depth: 3
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
